from selenium import webdriver
driver = webdriver.Chrome()
import time
driver.implicitly_wait(20)
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 1200);")
time.sleep(5)
selenium = driver.find_element_by_css_selector("#text-22-sub_row_1-0-2-0-0>div>ul>li>.button.product_type_simple.ajax_add_to_cart")
selenium.click()
time.sleep(3)
driver.execute_script("window.scrollBy(0, 400);")
time.sleep(3)
driver.find_element_by_css_selector(".reviews_tab").click()
time.sleep(5)
driver.execute_script("window.scrollBy(0, 600);")
driver.find_element_by_css_selector(".star-5").click()
comment_btn = driver.find_element_by_id("comment")
comment_btn.send_keys("Nice book!")
driver.find_element_by_id("author").send_keys("Svyatoslav")
driver.find_element_by_id("email").send_keys("svyatoslav@mail.ru")
driver.find_element_by_id("submit").click()
driver.quit()
